<a href="https://colab.research.google.com/github/90splayer/PyTorch/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
torch.manual_seed(0)
x = torch.rand(7,7)
x

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [5]:
torch.manual_seed(0)
y = torch.rand(1,7)
y

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [6]:
z = torch.matmul(x,y.T)
z

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [4]:
import torch

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# torch.cuda.manual_seed(1234)
# or, for all GPUs
# torch.cuda.manual_seed_all(1234)

'cuda'

In [6]:
torch.manual_seed(1234)
rand_tensor_A = torch.rand(2, 3)
torch.manual_seed(1234)
rand_tensor_B = torch.rand(2, 3)

print(rand_tensor_A)
print(rand_tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


In [8]:
tensor = torch.matmul(rand_tensor_A, rand_tensor_B.T)
tensor

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [9]:
print(torch.min(tensor), torch.max(tensor))

tensor(0.2161) tensor(0.6287)


In [13]:
print(tensor.argmax())
print(tensor.argmin())

tensor(3)
tensor(1)


In [16]:
torch.manual_seed(7)
new_rand = torch.rand(1, 1, 1, 10)
new_rand

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [17]:
squeeze_rand = new_rand.squeeze()
squeeze_rand
print(new_rand)
print(new_rand.shape)
print(squeeze_rand)
print(squeeze_rand.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
