<a href="https://colab.research.google.com/github/90splayer/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### creating tensors

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2146, 0.7685, 0.0331, 0.8260],
        [0.2325, 0.1522, 0.1442, 0.6494],
        [0.3442, 0.3856, 0.1079, 0.9358]])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
inc77 = torch.arange(start=0, end=1000, step=77)
inc77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)
one_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors
1. Tensors not right datatype - use `tensor.dtype`
2. Tensors not right shape - use `tensor.shape`
3. Tensors not on the right device - use `tensor.device`

In [33]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4144, 0.3731, 0.2252, 0.2166],
        [0.2946, 0.6218, 0.1930, 0.9535],
        [0.3046, 0.1496, 0.6911, 0.8650]])

In [34]:
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [35]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication

There are two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [38]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [39]:
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [40]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor.
#

In [42]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Transpose shapes: tensor_A = {tensor_A.T.shape}, tensor_B = {tensor_B.T.shape}")
torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Transpose shapes: tensor_A = torch.Size([2, 3]), tensor_B = torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [56]:
x = torch.arange(1, 100, 10)
print(x.dtype)
x

torch.int64


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [57]:
print(torch.min(x), x.min())
print(torch.max(x), x.max())
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

tensor(1) tensor(1)
tensor(91) tensor(91)


(tensor(46.), tensor(46.))

In [58]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [59]:
# tensor that has minimum value and return position
x.argmin()

tensor(0)

In [60]:
x[0]

tensor(1)

## Reshaping, stacking, squeezing and unsqueezing

Reshaping tensors: reshapes an input tensor to a defined shape
View tensors: return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking tensors: combine multiple tensors on top of each other
Squeeze tensors: remove all 1 dimensional axes from a tensor
Unsqueeze tensors: add a 1 dimensional axis to a tensor
Tensor permute: rearrange the dimensions of a tensor in a specified order

In [94]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [97]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 1] = 5
z, x

(tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.]))

In [93]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [98]:
# torch.squeeze() - removes all single dimensions from a target tensor
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
# torch.permute() - rearranges the dimensions of a target tensor in a specified order

x_reshaped.shape


torch.Size([1, 9])

In [100]:
x_reshaped.squeeze().shape

torch.Size([9])

In [101]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 1, 9])

In [103]:
x_original = torch.rand(size=(224, 224, 3)) # h,w,c
x_permuted = x_original.permute(2, 0, 1) # c,h,w
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))