<a href="https://colab.research.google.com/github/90splayer/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1633, 0.1819, 0.9309, 0.8217],
        [0.5482, 0.4340, 0.2211, 0.9277],
        [0.0541, 0.6863, 0.8158, 0.0624]])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [29]:
# Use torch.range()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
inc77 = torch.arange(start=0, end=1000, step=77)
inc77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [31]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)
one_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [3]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [4]:
float_32_tensor.dtype

torch.float32

In [5]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [6]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [7]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors
1. Tensors not right datatype - use `tensor.dtype`
2. Tensors not right shape - use `tensor.shape`
3. Tensors not on the right device - use `tensor.device`

In [15]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1821, 0.6736, 0.5619, 0.1914],
        [0.6493, 0.1044, 0.0961, 0.3546],
        [0.5783, 0.7184, 0.1280, 0.8794]])

In [13]:
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [16]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [17]:
tensor * 10

tensor([10, 20, 30])

In [19]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication

There are two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [20]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [21]:
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors